FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["Obsidian.Api/Obsidian.Api.csproj", "Obsidian.Api/"]
COPY ["Obsidian.Application/Obsidian.Application.csproj", "Obsidian.Application/"]
COPY ["Obsidian.Domain/Obsidian.Domain.csproj", "Obsidian.Domain/"]
COPY ["Obsidian.Infrastructure/Obsidian.Infrastructure.csproj", "Obsidian.Infrastructure/"]
RUN dotnet restore "Obsidian.Api/Obsidian.Api.csproj"

COPY . .
WORKDIR "/src/Obsidian.Api"
RUN dotnet publish "Obsidian.Api.csproj" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
EXPOSE 8080

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Obsidian.Api.dll"]
